<?php

return [
    'production' => false,
    'baseUrl' => '',
    'siteName' => 'Partners Portal',
    'siteDescription' => '合作夥伴入口網站',
    'description' => '合作夥伴入口網站',
    'language' => 'zh-Hant',
    'collections' => [],
    'locales' => ['TW', 'EN', 'JP'],
    'partner' => [
        'company' => '經銷商公司名稱',
        'role' => '總管理者',
        'contact' => '王小明',
        'phone' => '02-1234-5678',
    ],
    'defaultPreviewRole' => 'admin',
    'roles' => [
        'admin' => [
            'label' => '總管理者',
            'nav' => ['/', '/opportunities', '/products', '/training', '/marketing', '/support', '/profile'],
            'can' => [
                'opportunity.create',
                'opportunity.export',
                'opportunity.status.edit',
                'opportunity.actions',
                'opportunity.review',
                'profile.manage',
            ],
        ],
        'user' => [
            'label' => '一般使用者',
            'nav' => ['/', '/opportunities', '/products', '/training', '/marketing', '/support'],
            'can' => [
                'opportunity.view',
                'opportunity.create',
                'opportunity.export',
            ],
        ],
    ],
    'overviewModules' => [
        [
            'label' => '商機中心',
            'path' => '/opportunities',
            'description' => "商機註冊 • 查詢\n修改 • 續期",
        ],
        [
            'label' => '產品資訊中心',
            'path' => '/products',
            'description' => "新品 • EOL／EOS\n版本更新公告",
        ],
        [
            'label' => '教育訓練中心',
            'path' => '/training',
            'description' => '線上課程',
        ],
        [
            'label' => '行銷資源中心',
            'path' => '/marketing',
            'description' => "文件 • 簡報\nCampaign Kit",
        ],
        [
            'label' => '技術支援中心',
            'path' => '/support',
            'description' => "FAQ 與材料\n新增技術工單",
        ],
    ],
    'appNav' => [
        ['label' => '概覽', 'path' => '/', 'icon' => 'layout-dashboard'],
        ['label' => '商機中心', 'path' => '/opportunities', 'icon' => 'briefcase'],
        ['label' => '產品資訊中心', 'path' => '/products', 'icon' => 'package'],
        ['label' => '教育訓練中心', 'path' => '/training', 'icon' => 'graduation-cap'],
        ['label' => '行銷資源中心', 'path' => '/marketing', 'icon' => 'megaphone'],
        ['label' => '技術支援中心', 'path' => '/support', 'icon' => 'headset'],
        ['label' => '夥伴資料', 'path' => '/profile', 'icon' => 'id-card'],
    ],
    'pageBreadcrumbs' => [
        '/' => [
            ['label' => '概覽'],
        ],
        'opportunities' => [
            ['label' => '商機中心'],
        ],
        'opportunities/create' => [
            ['label' => '商機中心', 'path' => '/opportunities'],
            ['label' => '新增商機', 'attr' => 'data-page-title'],
        ],
        'opportunities/review' => [
            ['label' => '商機中心', 'path' => '/opportunities'],
            ['label' => '商機審核', 'attr' => 'data-review-crumb-kind'],
            ['label' => '', 'attr' => 'data-review-id-crumb', 'uppercase' => true],
        ],
        'opportunities/renew' => [
            ['label' => '商機中心', 'path' => '/opportunities'],
            ['label' => '商機續期'],
        ],
        'products' => [
            ['label' => '產品資訊中心'],
        ],
        'marketing' => [
            ['label' => '行銷資源中心'],
        ],
        'training' => [
            ['label' => '教育訓練中心'],
            ['label' => '平台導覽', 'attr' => 'data-training-crumb', 'current' => true],
        ],
    ],
    'opportunityStats' => [
        ['label' => '進行中商機', 'count' => 12, 'tone' => 'default'],
        ['label' => '審核中', 'count' => 2, 'tone' => 'warning'],
        ['label' => '暫存檔', 'count' => 1, 'tone' => 'default'],
        ['label' => '30天內即將到期', 'count' => 2, 'tone' => 'danger'],
    ],
    'opportunityStatuses' => [
        ['value' => 'draft', 'label' => '暫存', 'icon' => 'file-pen-line'],
        ['value' => 'approved', 'label' => '已核准', 'icon' => 'check-circle'],
        ['value' => 'reviewing', 'label' => '審核中', 'icon' => 'clock'],
        ['value' => 'rejected', 'label' => '退回補件', 'icon' => 'file-warning'],
        ['value' => 'expiring', 'label' => '即將到期', 'icon' => 'alert-circle'],
        ['value' => 'expired', 'label' => '已到期', 'icon' => 'circle-x'],
        ['value' => 'cancelled', 'label' => '已取消', 'icon' => 'ban'],
        ['value' => 'completed', 'label' => '已結案', 'icon' => 'circle-check'],
        ['value' => 'invalid', 'label' => '已失效', 'icon' => 'circle-off'],
    ],
    'opportunityDealerLabels' => [
        'oem' => '原廠業務',
        'tw' => '台灣經銷商',
        'overseas' => '海外經銷商',
    ],
    'opportunityFilters' => [
        [
            'key' => 'dealer',
            'label' => '所屬',
            'options' => [
                ['value' => 'all', 'label' => '全部'],
                ['value' => 'oem', 'label' => '原廠業務'],
                ['value' => 'tw', 'label' => '台灣經銷商'],
                ['value' => 'overseas', 'label' => '海外經銷商'],
            ],
        ],
        [
            'key' => 'status',
            'label' => '商機狀態',
            'options' => [
                ['value' => 'all', 'label' => '全部'],
                ['value' => 'draft', 'label' => '暫存'],
                ['value' => 'approved', 'label' => '已核准'],
                ['value' => 'reviewing', 'label' => '審核中'],
                ['value' => 'rejected', 'label' => '退回補件'],
                ['value' => 'expiring', 'label' => '即將到期'],
                ['value' => 'expired', 'label' => '已到期'],
                ['value' => 'cancelled', 'label' => '已取消'],
                ['value' => 'completed', 'label' => '已結案'],
                ['value' => 'invalid', 'label' => '已失效'],
            ],
        ],
    ],
    'opportunities' => [
        [
            'id' => 'DRAFT-001',
            'customer' => '（暫存）尚未填寫完整',
            'amount' => '-',
            'amountValue' => 0,
            'status' => 'draft',
            'dealer' => 'tw',
            'protection' => '-',
        ],
        [
            'id' => 'N260728005',
            'customer' => 'A 公司',
            'amount' => '$500,000',
            'amountValue' => 500000,
            'status' => 'approved',
            'dealer' => 'tw',
            'protection' => '2026-09-30',
        ],
        [
            'id' => 'N260728004',
            'customer' => 'B 科技',
            'amount' => '$80,000',
            'amountValue' => 80000,
            'status' => 'reviewing',
            'dealer' => 'oem',
            'protection' => '-',
        ],
        [
            'id' => 'N260728002',
            'customer' => 'D 數位',
            'amount' => '$350,000',
            'amountValue' => 350000,
            'status' => 'rejected',
            'dealer' => 'tw',
            'protection' => '-',
        ],
        [
            'id' => 'N260728001',
            'customer' => 'C 集團',
            'amount' => '$1,200,000',
            'amountValue' => 1200000,
            'status' => 'expiring',
            'dealer' => 'overseas',
            'protection' => '2026-07-15',
        ],
        [
            'id' => 'N260728003',
            'customer' => 'E 集團',
            'amount' => '$750,000',
            'amountValue' => 750000,
            'status' => 'expired',
            'dealer' => 'oem',
            'protection' => '2026-07-15',
        ],
        [
            'id' => 'N260728006',
            'customer' => 'F 製造',
            'amount' => '$420,000',
            'amountValue' => 420000,
            'status' => 'cancelled',
            'dealer' => 'tw',
            'protection' => '-',
        ],
        [
            'id' => 'N260728007',
            'customer' => 'G 醫院',
            'amount' => '$980,000',
            'amountValue' => 980000,
            'status' => 'completed',
            'dealer' => 'oem',
            'protection' => '-',
        ],
        [
            'id' => 'N260728008',
            'customer' => 'H 零售',
            'amount' => '$260,000',
            'amountValue' => 260000,
            'status' => 'invalid',
            'dealer' => 'overseas',
            'protection' => '-',
        ],
    ],
    'opportunityPagination' => [
        'summary' => 'Showing 1-9 of 9 results',
        'pages' => [1],
        'current' => 1,
    ],
    'productTabs' => [
        ['value' => 'new', 'label' => '新產品公告'],
        ['value' => 'eol', 'label' => 'EOL 停產'],
        ['value' => 'eos', 'label' => 'EOS 停止支援'],
        ['value' => 'update', 'label' => '版本更新'],
    ],
    'productCategories' => [
        'new' => ['label' => '新產品', 'class' => 'text-brand2'],
        'eol' => ['label' => 'EOL', 'class' => 'text-brand2'],
        'eos' => ['label' => 'EOS', 'class' => 'text-brand2'],
        'update' => ['label' => '版本更新', 'class' => 'text-brand2'],
    ],
    'productAnnouncements' => [
        [
            'date' => '2026-06-15',
            'category' => 'new',
            'title' => '新產品公告：UPAS 雲端資安平台 7.0 正式上市',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-05-20',
            'category' => 'eol',
            'title' => '產品停產公告：UPAS NOC 5.x 系列將於 2026/12/31 停止銷售',
            'attachment' => 'link',
        ],
        [
            'date' => '2026-05-02',
            'category' => 'new',
            'title' => '新產品公告：UPAS OT 資安偵測方案正式上市',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-04-08',
            'category' => 'eos',
            'title' => '產品停止支援公告：UPAS NOC 4.x 系列將於 2026/09/30 停止技術支援',
            'attachment' => 'link',
        ],
        [
            'date' => '2026-03-12',
            'category' => 'update',
            'title' => '版本更新：UPAS NOC 7.0 Patch 2026-03 安全性更新',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-02-18',
            'category' => 'new',
            'title' => '新產品公告：UPAS 資安監控模組正式推出',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-02-01',
            'category' => 'eos',
            'title' => '產品停止支援公告：UPAS NOC 3.x 系列技術支援即將結束',
            'attachment' => 'link',
        ],
        [
            'date' => '2026-01-25',
            'category' => 'update',
            'title' => 'UPAS NOC 7.0 ISO27001 符規對照表',
            'attachment' => 'link',
        ],
        [
            'date' => '2026-01-08',
            'category' => 'eol',
            'title' => '產品停產公告：UPAS Scanner 3.x 將於 2026/10/31 停止銷售',
            'attachment' => 'link',
        ],
        [
            'date' => '2025-12-18',
            'category' => 'update',
            'title' => '版本更新：UPAS NOC 7.0 Patch 2025-12 功能增強',
            'attachment' => 'download',
        ],
        [
            'date' => '2025-12-10',
            'category' => 'new',
            'title' => '新產品公告：UPAS NOC 雲端備援模組開放申請',
            'attachment' => 'link',
        ],
        [
            'date' => '2025-11-15',
            'category' => 'eol',
            'title' => '產品停產公告：UPAS Appliance 2.x 硬體型號停止接單',
            'attachment' => 'download',
        ],
    ],
    'productPagination' => [
        'summary' => 'Showing 1-4 of 4 results',
        'pages' => [1],
        'current' => 1,
    ],
    'marketingTabs' => [
        ['value' => 'doc', 'label' => '文件'],
        ['value' => 'deck', 'label' => '簡報'],
        ['value' => 'kit', 'label' => 'Campaign Kit'],
    ],
    'marketingCategories' => [
        'doc' => ['label' => '文件'],
        'deck' => ['label' => '簡報'],
        'kit' => ['label' => 'Campaign Kit'],
    ],
    'marketingResources' => [
        [
            'date' => '2026-08-20',
            'category' => 'doc',
            'title' => 'UPAS NOC 7.0 產品規格書',
            'format' => 'PDF',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-08-12',
            'category' => 'deck',
            'title' => 'UPAS NOC 7.0 銷售簡報',
            'format' => 'PPTX',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-08-01',
            'category' => 'kit',
            'title' => '2026 Q3 通路活動素材包',
            'format' => 'ZIP',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-07-22',
            'category' => 'doc',
            'title' => 'UPAS 解決方案白皮書',
            'format' => 'PDF',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-07-15',
            'category' => 'deck',
            'title' => '競爭分析與話術卡',
            'format' => 'PPTX',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-07-08',
            'category' => 'kit',
            'title' => '社群貼文與 Banner 套件',
            'format' => 'ZIP',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-06-30',
            'category' => 'doc',
            'title' => '通路價格表 2026 Q3',
            'format' => 'XLSX',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-06-18',
            'category' => 'deck',
            'title' => 'OT 資安方案介紹簡報',
            'format' => 'PPTX',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-06-10',
            'category' => 'kit',
            'title' => 'Email 行銷範本與簽名檔',
            'format' => 'ZIP',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-05-28',
            'category' => 'doc',
            'title' => 'UPAS OT 資安偵測方案規格書',
            'format' => 'PDF',
            'attachment' => 'link',
        ],
        [
            'date' => '2026-05-16',
            'category' => 'deck',
            'title' => '經銷商新人產品訓練簡報',
            'format' => 'PPTX',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-05-02',
            'category' => 'kit',
            'title' => '展會用產品海報與易拉展',
            'format' => 'ZIP',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-04-20',
            'category' => 'doc',
            'title' => 'ISO27001 符規對照表',
            'format' => 'PDF',
            'attachment' => 'link',
        ],
        [
            'date' => '2026-04-08',
            'category' => 'deck',
            'title' => 'UPAS 雲端備援模組簡報',
            'format' => 'PPTX',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-03-25',
            'category' => 'kit',
            'title' => '品牌 Logo 與使用規範包',
            'format' => 'ZIP',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-03-12',
            'category' => 'doc',
            'title' => '成功案例：醫療網段 IP 管理導入',
            'format' => 'PDF',
            'attachment' => 'download',
        ],
        [
            'date' => '2026-02-27',
            'category' => 'deck',
            'title' => '訪客管理方案銷售簡報',
            'format' => 'PPTX',
            'attachment' => 'link',
        ],
        [
            'date' => '2026-02-10',
            'category' => 'kit',
            'title' => '新品上市 Campaign Kit：雲端資安平台 7.0',
            'format' => 'ZIP',
            'attachment' => 'download',
        ],
    ],
    'trainingCourses' => [
        [
            'id' => 'onboarding',
            'label' => '夥伴入門',
            'icon' => 'compass',
            'articles' => [
                [
                    'id' => 'portal-guide',
                    'label' => '平台導覽',
                    'title' => '認識 Partners Portal',
                    'level' => '入門',
                    'duration' => '8 分鐘',
                    'updated' => '2026-08-18',
                    'cover' => 'training/cover-portal.svg',
                    'coverAlt' => 'Partners Portal 功能區塊示意',
                    'lead' => '帶你快速走完合作夥伴入口的六大功能區塊，以及總管理者與一般使用者看到的差異。',
                    'blocks' => [
                        ['type' => 'p', 'text' => 'Partners Portal 是給經銷夥伴使用的工作台。左側主選單可進入各中心；右上角顯示目前公司與角色。本頁右側的課程內容會隨左側目錄切換。'],
                        ['type' => 'h2', 'text' => '你可以完成什麼'],
                        ['type' => 'ul', 'items' => [
                            '商機中心：註冊、查詢、續期與審核',
                            '產品資訊中心：新品、EOL／EOS 與版本更新',
                            '教育訓練中心：線上課程與認證導讀',
                            '行銷資源中心：文件、簡報與 Campaign Kit',
                            '技術支援中心：FAQ 與技術工單',
                            '夥伴資料：公司與聯絡人資訊',
                        ]],
                        ['type' => 'callout', 'text' => '演示時可使用左下角「預覽身分」切換總管理者與業務／經銷商，觀察選單與操作差異。'],
                    ],
                ],
                [
                    'id' => 'opportunity-flow',
                    'label' => '商機報備流程',
                    'title' => '商機報備怎麼走',
                    'level' => '入門',
                    'duration' => '10 分鐘',
                    'updated' => '2026-08-20',
                    'cover' => 'training/cover-flow.svg',
                    'coverAlt' => '商機報備四步驟流程',
                    'lead' => '從填寫註冊到保護期生效，掌握每個關卡要準備的資料，減少退回補件。',
                    'blocks' => [
                        ['type' => 'p', 'text' => '商機需先完成報備並通過審核，才會進入保護期。資料愈完整，審核愈快；Key Man、時程與產品組合是最常被退回的欄位。'],
                        [
                            'type' => 'image',
                            'src' => 'training/diagram-opp-flow.svg',
                            'alt' => '填寫、送審、審核、保護期四個關卡',
                            'caption' => '標準路徑：填寫註冊 → 送出審核 → 原廠審核 → 保護期生效',
                        ],
                        [
                            'type' => 'steps',
                            'items' => [
                                ['title' => '填寫註冊', 'text' => '選擇商機來源、客戶資料、產品與數量級距，並附上需求說明。'],
                                ['title' => '送出審核', 'text' => '送出後狀態改為審核中，此時仍可於列表追蹤進度。'],
                                ['title' => '原廠審核', 'text' => '通過後會指派原廠業務並產生報備編號；不足則退回補件。'],
                                ['title' => '保護期生效', 'text' => '核准後開始計算保護期，到期前可申請續期。'],
                            ],
                        ],
                        ['type' => 'callout', 'text' => '若狀態為「退回補件」，請依審核意見補齊資料後再送出，無需重新開立一筆商機。'],
                    ],
                ],
                [
                    'id' => 'partner-rights',
                    'label' => '權益與保護期',
                    'title' => '商機保護期與夥伴權益',
                    'level' => '入門',
                    'duration' => '6 分鐘',
                    'updated' => '2026-07-30',
                    'cover' => 'training/cover-rights.svg',
                    'coverAlt' => '保護期與權益示意',
                    'lead' => '了解保護期怎麼算、什麼情況會失效，以及夥伴可使用的資源範圍。',
                    'blocks' => [
                        ['type' => 'p', 'text' => '保護期自審核通過當日起算。列表會標示即將到期案件，建議在到期前 14 天提出續期，並補充最新進度。'],
                        ['type' => 'h2', 'text' => '保護期常見規則'],
                        ['type' => 'ul', 'items' => [
                            '同一客戶、相同產品線原則上不可重複報備',
                            '保護期結束且未續期，案件改為已到期',
                            '客戶確認無需求或重複商機，可能改為已失效',
                            '夥伴可主動取消尚未成交的報備',
                        ]],
                        ['type' => 'h2', 'text' => '夥伴可使用的資源'],
                        ['type' => 'ul', 'items' => [
                            '產品規格書、銷售簡報與案例',
                            '本中心的線上課程與認證導讀',
                            '技術支援 FAQ 與工單',
                        ]],
                        ['type' => 'callout', 'text' => '總管理者可檢視審核紀錄與指派業務；一般使用者以報備、查詢與續期為主。'],
                    ],
                ],
            ],
        ],
        [
            'id' => 'products',
            'label' => '產品訓練',
            'icon' => 'cpu',
            'articles' => [
                [
                    'id' => 'iplocator',
                    'label' => 'IPLocator 位址解析',
                    'title' => 'IPLocator IP 位址解析模組',
                    'level' => '產品',
                    'duration' => '12 分鐘',
                    'updated' => '2026-08-01',
                    'cover' => 'training/cover-network.svg',
                    'coverAlt' => '跨網段位址盤點示意',
                    'lead' => '協助客戶把散落在各網段的 IP 資產一次看清楚，是多數導入案的第一個切點。',
                    'blocks' => [
                        ['type' => 'p', 'text' => 'IPLocator 用來盤點與解析 IP 位址，讓資訊單位掌握「誰在用哪個位址」。適合正在做資產盤點、稽核或網段重整的客戶。'],
                        [
                            'type' => 'image',
                            'src' => 'training/diagram-network.svg',
                            'alt' => '中央管理與各網段節點的對應關係',
                            'caption' => '以中央管理節點串起各網段裝置，先盤點再談控管。',
                        ],
                        ['type' => 'h2', 'text' => '適合什麼客戶'],
                        ['type' => 'ul', 'items' => [
                            '多棟辦公或跨據點、IP 資料分散在試算表',
                            '即將導入 ISO 27001 或內部稽核',
                            '規劃與 ARPScanner、MACManager 一併評估',
                        ]],
                        ['type' => 'callout', 'text' => '銷售話術可先問「現在 IP 清單多久更新一次」，通常能快速對到痛點。'],
                    ],
                ],
                [
                    'id' => 'arpscanner',
                    'label' => 'ARPScanner IP 管理',
                    'title' => 'ARPScanner IP 管理系統',
                    'level' => '產品',
                    'duration' => '12 分鐘',
                    'updated' => '2026-08-01',
                    'cover' => 'training/cover-network.svg',
                    'coverAlt' => 'IP 管理節點示意',
                    'lead' => '在位址盤點之後，進一步做衝突偵測與日常管理，是中大型網路常見的下一步。',
                    'blocks' => [
                        ['type' => 'p', 'text' => 'ARPScanner 協助偵測 IP 衝突、掌握連線狀態，減少「位址被佔用卻找不到人」的工單。常與 IPLocator 搭配提案。'],
                        ['type' => 'h2', 'text' => '銷售重點'],
                        ['type' => 'ul', 'items' => [
                            '降低人工作業與重複派工',
                            '對製造、醫療等 24 小時運作環境特別有感',
                            '可依節點數量選擇數量級距，方便報價',
                        ]],
                        ['type' => 'callout', 'text' => '提案時請一併確認客戶現有網管工具，避免功能重疊造成疑慮。'],
                    ],
                ],
                [
                    'id' => 'dhcpmanager',
                    'label' => 'DHCPManager 管理',
                    'title' => 'DHCPManager DHCP 管理系統',
                    'level' => '產品',
                    'duration' => '10 分鐘',
                    'updated' => '2026-07-22',
                    'cover' => 'training/cover-network.svg',
                    'coverAlt' => 'DHCP 管理架構示意',
                    'lead' => '當客戶的位址發放仍靠多台 DHCP、政策不一致時，這門課幫你對齊話術與導入順序。',
                    'blocks' => [
                        ['type' => 'p', 'text' => 'DHCPManager 讓位址發放政策可被集中檢視與調整，適合據點多、租約衝突頻繁的環境。'],
                        ['type' => 'h2', 'text' => '導入時要先問'],
                        ['type' => 'ul', 'items' => [
                            'DHCP 伺服器數量與分布',
                            '是否已有固定／浮動位址的區隔',
                            '與現有防火牆或網管的整合需求',
                        ]],
                        ['type' => 'callout', 'text' => '大型案建議先 POC 單一網段，再擴到全區，較容易過決策。'],
                    ],
                ],
                [
                    'id' => 'macmanager',
                    'label' => 'MACManager 位址管理',
                    'title' => 'MACManager MAC 位址管理系統',
                    'level' => '產品',
                    'duration' => '10 分鐘',
                    'updated' => '2026-07-22',
                    'cover' => 'training/cover-network.svg',
                    'coverAlt' => 'MAC 位址管理示意',
                    'lead' => '訪客、BYOD 與設備准入是常見切點，適合與 IP 管理方案一起談。',
                    'blocks' => [
                        ['type' => 'p', 'text' => 'MACManager 用來管理裝置位址與准入政策，常出現在訪客管理、門市與醫療場域。'],
                        ['type' => 'h2', 'text' => '常見場景'],
                        ['type' => 'ul', 'items' => [
                            '訪客裝置需暫時上網且要留下紀錄',
                            '內部設備要避免未授權接入',
                            '與 IPLocator 一併做資產與准入閉環',
                        ]],
                        ['type' => 'callout', 'text' => '若客戶已在評估訪客管理，請同步準備行銷資源中心的方案簡報。'],
                    ],
                ],
            ],
        ],
        [
            'id' => 'sales',
            'label' => '銷售與案例',
            'icon' => 'target',
            'articles' => [
                [
                    'id' => 'discovery',
                    'label' => '需求訪談技巧',
                    'title' => '需求訪談怎麼問',
                    'level' => '銷售',
                    'duration' => '9 分鐘',
                    'updated' => '2026-08-12',
                    'cover' => 'training/cover-sales.svg',
                    'coverAlt' => '訪談紀錄與重點整理示意',
                    'lead' => '用四個問題把現況、痛點、決策鏈與時程問清楚，報備資料也會比較完整。',
                    'blocks' => [
                        ['type' => 'p', 'text' => '訪談不是一次介紹完所有產品。先確認客戶現在怎麼管 IP／MAC，再對應模組，最後才談時程與預算。'],
                        [
                            'type' => 'steps',
                            'items' => [
                                ['title' => '現況盤點', 'text' => '清單在哪、多久更新、由誰維護。'],
                                ['title' => '痛點', 'text' => '衝突、找不到人、稽核抽問時交不出資料。'],
                                ['title' => '決策鏈', 'text' => '承辦人與 Key Man 是否同一人，誰能拍板。'],
                                ['title' => '時程', 'text' => 'POC、決策、交貨與上線的大致月份。'],
                            ],
                        ],
                        ['type' => 'callout', 'text' => '這四項正好對應商機註冊欄位。訪談當下記下來，可減少退回補件。'],
                    ],
                ],
                [
                    'id' => 'hospital-case',
                    'label' => '醫療業導入案例',
                    'title' => '成功案例：醫療網段 IP 管理',
                    'level' => '案例',
                    'duration' => '7 分鐘',
                    'updated' => '2026-06-18',
                    'cover' => 'training/cover-sales.svg',
                    'coverAlt' => '案例簡報示意',
                    'lead' => '以醫療場域為例，說明如何從網段盤點走到 DHCP 管理，並對應商機中心的結案情境。',
                    'blocks' => [
                        ['type' => 'p', 'text' => '醫療環境網段多、設備異質，IP 衝突會直接影響診療流程。此案先以 IPLocator 完成盤點，再導入 DHCPManager 統一發放政策。'],
                        ['type' => 'h2', 'text' => '為什麼成交'],
                        ['type' => 'ul', 'items' => [
                            '對齊稽核與營運不中斷兩項需求',
                            'POC 先選非急診網段，降低風險',
                            '原廠與夥伴共同參與決策會議',
                        ]],
                        ['type' => 'quote', 'text' => '先把位址看清楚，後續的准入與發放才有依據。', 'cite' => 'G 醫院　資訊室'],
                        ['type' => 'callout', 'text' => '完整簡報與規格書可至行銷資源中心下載。'],
                    ],
                ],
                [
                    'id' => 'compete',
                    'label' => '競爭分析要點',
                    'title' => '面對競爭時怎麼說',
                    'level' => '銷售',
                    'duration' => '8 分鐘',
                    'updated' => '2026-07-15',
                    'cover' => 'training/cover-sales.svg',
                    'coverAlt' => '競爭分析資料示意',
                    'lead' => '客戶同時評估其他網管或 NAC 時，把差異說在「盤點完整性」與「落地支援」，而不是比功能清單。',
                    'blocks' => [
                        ['type' => 'p', 'text' => '競爭不一定要正面否定對方。先確認客戶真正要解決的是盤點、衝突還是准入，再對應 UPAS 模組組合。'],
                        ['type' => 'h2', 'text' => '建議強調'],
                        ['type' => 'ul', 'items' => [
                            'IP／MAC 資產可視性，而不只是阻擋',
                            '可分模組導入，降低一次換系統的阻力',
                            '在地支援與 Partners Portal 的報備、訓練資源',
                        ]],
                        ['type' => 'callout', 'text' => '行銷資源中心有「競爭分析與話術卡」，可與本課一起使用。'],
                    ],
                ],
            ],
        ],
        [
            'id' => 'cert',
            'label' => '認證課程',
            'icon' => 'badge-check',
            'articles' => [
                [
                    'id' => 'sales-cert',
                    'label' => '銷售認證導讀',
                    'title' => '銷售認證考前導讀',
                    'level' => '認證',
                    'duration' => '15 分鐘',
                    'updated' => '2026-08-05',
                    'cover' => 'training/cover-cert.svg',
                    'coverAlt' => '認證通過示意',
                    'lead' => '整理銷售認證的出題範圍與準備順序，建議先完成本中心「夥伴入門」與「銷售與案例」。',
                    'blocks' => [
                        ['type' => 'p', 'text' => '銷售認證檢核你是否能獨立完成需求訪談、模組對應與商機報備。通過後可在對外場合使用認證夥伴識別。'],
                        ['type' => 'h2', 'text' => '準備範圍'],
                        ['type' => 'ul', 'items' => [
                            '六大功能區塊與角色權限差異',
                            '商機報備欄位與保護期規則',
                            '四個核心產品的適用場景',
                            '醫療與跨據點兩類案例話術',
                        ]],
                        ['type' => 'callout', 'text' => '本頁為示意導讀。正式考場與報名流程將由原廠訓練窗口另行通知。'],
                    ],
                ],
                [
                    'id' => 'tech-cert',
                    'label' => '技術認證實作',
                    'title' => '技術認證實作指引',
                    'level' => '認證',
                    'duration' => '20 分鐘',
                    'updated' => '2026-08-05',
                    'cover' => 'training/cover-cert.svg',
                    'coverAlt' => '技術認證示意',
                    'lead' => '技術認證著重 POC 環境準備、盤點流程與常見問題排除，適合售前與導入工程師。',
                    'blocks' => [
                        ['type' => 'p', 'text' => '實作評量會要求你完成小型網段盤點，並說明如何把結果對應到 IPLocator 與 ARPScanner 的下一步。'],
                        [
                            'type' => 'steps',
                            'items' => [
                                ['title' => '準備環境', 'text' => '確認測試網段、帳號權限與現有 DHCP 範圍。'],
                                ['title' => '執行盤點', 'text' => '產出位址清單，標示衝突與不明裝置。'],
                                ['title' => '對應方案', 'text' => '說明哪些問題由哪個模組承接。'],
                                ['title' => '回報結果', 'text' => '用客戶聽得懂的語言整理 POC 結論。'],
                            ],
                        ],
                        ['type' => 'callout', 'text' => '實作細節若與現場環境衝突，請改走技術支援中心開立工單。'],
                    ],
                ],
            ],
        ],
    ],
    'opportunitySources' => [
        ['value' => 'self', 'label' => '自行開發'],
        ['value' => 'oem', 'label' => '原廠派發'],
    ],
    'opportunityCustomerRelations' => [
        ['value' => 'first', 'label' => '第一次接洽'],
        ['value' => 'repeat', 'label' => '多次接洽(未成交)'],
        ['value' => 'other', 'label' => '其他'],
    ],
    'opportunityProducts' => [
        'IPLocator IP位址解析模組',
        'ARPScanner IP管理系統',
        'DHCPManager DHCP管理系統',
        'MACManager MAC位址管理系統',
    ],
    'opportunityUnitRanges' => [
        '0-499',
        '500-999',
        '1000-1999',
        '2000-4999',
        '5000+',
    ],
    'opportunityDefaultProducts' => [
        ['product' => 'IPLocator IP位址解析模組', 'units' => '0-499'],
        ['product' => 'ARPScanner IP管理系統', 'units' => '0-499'],
    ],
    'opportunityDates' => [
        ['name' => 'poc_date', 'label' => '預計 POC 日'],
        ['name' => 'decision_date', 'label' => '預計決策日'],
        ['name' => 'delivery_date', 'label' => '預計交貨日'],
        ['name' => 'complete_date', 'label' => '預計完成日'],
    ],
    'opportunityCustomerFields' => [
        ['name' => 'customer_company', 'label' => '客戶公司名稱', 'placeholder' => '請輸入完整公司名稱，以確保權益', 'type' => 'text'],
        ['name' => 'customer_address', 'label' => '客戶公司地址', 'placeholder' => '請輸入完整公司地址', 'type' => 'text'],
        ['name' => 'contact_name', 'label' => '客戶主要聯絡人／承辦人', 'placeholder' => '請輸入姓名', 'type' => 'text'],
        ['name' => 'contact_title', 'label' => '客戶主要聯絡人 職稱／部門', 'placeholder' => '例：資訊部經理', 'type' => 'text'],
        ['name' => 'contact_phone', 'label' => '客戶主要聯絡人電話', 'placeholder' => '請輸入電話或分機', 'type' => 'tel'],
        ['name' => 'contact_email', 'label' => '客戶主要聯絡人信箱', 'placeholder' => 'name@customer.com', 'type' => 'email'],
    ],
    'opportunityKeyManFields' => [
        ['name' => 'keyman_name', 'label' => 'Key Man', 'placeholder' => '請填寫 Key Man 名稱', 'type' => 'text'],
        ['name' => 'keyman_phone', 'label' => 'Key Man 聯絡電話', 'placeholder' => '請輸入電話或分機', 'type' => 'tel'],
        ['name' => 'keyman_email', 'label' => 'Key Man 聯絡 Email', 'placeholder' => 'name@customer.com', 'type' => 'email'],
    ],
    'opportunityReviewResults' => [
        ['value' => 'approved', 'label' => '審核通過', 'status' => 'approved', 'statusLabel' => '已核准', 'allowResubmit' => false],
        ['value' => 'insufficient', 'label' => '資料不足，請補充', 'status' => 'rejected', 'statusLabel' => '退回補件', 'allowResubmit' => true],
        ['value' => 'need_confirm', 'label' => '商機資訊需確認', 'status' => 'rejected', 'statusLabel' => '退回補件', 'allowResubmit' => true],
        ['value' => 'duplicate', 'label' => '已有相同／重複商機', 'status' => 'invalid', 'statusLabel' => '已失效', 'allowResubmit' => false],
        ['value' => 'not_eligible', 'label' => '不符合商機報備條件', 'status' => 'invalid', 'statusLabel' => '已失效', 'allowResubmit' => false],
        ['value' => 'no_demand', 'label' => '商機已失效／暫無需求', 'status' => 'invalid', 'statusLabel' => '已失效', 'allowResubmit' => false],
        ['value' => 'rejected', 'label' => '審核不通過', 'status' => 'invalid', 'statusLabel' => '已失效', 'allowResubmit' => false],
        ['value' => 'other', 'label' => '其他', 'status' => 'rejected', 'statusLabel' => '退回補件', 'allowResubmit' => true],
    ],
    'opportunityOemSalesOptions' => [
        ['value' => 'wang', 'label' => '王小華'],
        ['value' => 'chen', 'label' => '陳志明'],
        ['value' => 'lin', 'label' => '林佳穎'],
        ['value' => 'huang', 'label' => '黃建宏'],
        ['value' => 'wu', 'label' => '吳佩珊'],
    ],
    'opportunityCatalog' => [
        'N260728005' => [
            'id' => 'N260728005',
            'status' => 'approved',
            'statusLabel' => '已核准',
            'title' => 'A 公司 | 資安基礎建設升級案',
            'dealerName' => '台灣 XX 科技',
            'submittedAt' => '2026/07/18 14:20',
            'customer_company' => 'A 公司',
            'tax_id' => '24567890',
            'amount' => 'NT$ 500,000',
            'amountValue' => 500000,
            'close_date' => '2026 / 10 / 15',
            'product_line' => 'IPLocator、MACManager',
            'requirement' => '客戶規劃全公司 IP／MAC 資產盤點，並評估導入位址管理方案。',
            'attachment' => ['name' => '需求說明.pdf', 'url' => '#'],
            'booking_code' => 'N260728005',
            'dealer' => 'tw',
            'protection' => '2026-09-30',
            'review' => [
                'result' => 'approved',
                'resultLabel' => '審核通過',
                'sales' => 'wang',
                'salesLabel' => '王小華',
                'bookingCode' => 'N260728005',
                'note' => '資料齊全，已核准並指派原廠業務。',
                'reviewedAt' => '2026/07/19 10:05',
            ],
            'form' => [
                'source' => 'self',
                'oem_sales' => '王小華',
                'customer_relation' => 'first',
                'competitors' => '',
                'products' => ['IPLocator IP位址解析模組', 'MACManager MAC位址管理系統'],
                'units' => ['1000-1999', '500-999'],
                'fields' => [
                    'oem_sales' => '王小華',
                    'customer_company' => 'A 公司',
                    'customer_address' => '台北市內湖區',
                    'contact_name' => '林經理',
                    'contact_title' => '資訊部經理',
                    'contact_phone' => '02-2658-1234',
                    'contact_email' => 'lin@a-corp.com',
                    'keyman_name' => '黃副總',
                    'keyman_phone' => '02-2658-1000',
                    'keyman_email' => 'huang@a-corp.com',
                    'poc_date' => '2026-08-01',
                    'decision_date' => '2026-10-15',
                    'delivery_date' => '2026-11-01',
                    'complete_date' => '2026-12-01',
                ],
            ],
        ],
        'N260728004' => [
            'id' => 'N260728004',
            'status' => 'reviewing',
            'statusLabel' => '審核中',
            'title' => 'B 科技 | 網路設備盤點與存取控管案',
            'dealerName' => '台灣 XX 科技',
            'submittedAt' => '2026/07/22 09:40',
            'customer_company' => 'B 科技',
            'tax_id' => '12345678',
            'amount' => 'NT$ 350,000',
            'amountValue' => 350000,
            'close_date' => '2026 / 09 / 30',
            'product_line' => 'IP/MAC、GAM 訪客管理',
            'requirement' => '客戶希望盤點跨據點設備，並評估導入網路存取控管；目前已完成初步需求訪談。',
            'attachment' => ['name' => '客戶需求規格書.pdf', 'url' => '#'],
            'booking_code' => 'N260728004',
            'dealer' => 'oem',
            'protection' => '-',
            'review' => null,
            'form' => [
                'source' => 'oem',
                'oem_sales' => '王小華',
                'customer_relation' => 'repeat',
                'competitors' => '客戶同時評估其他網路存取控管方案',
                'products' => ['IPLocator IP位址解析模組', 'MACManager MAC位址管理系統'],
                'units' => ['500-999', '0-499'],
                'fields' => [
                    'oem_sales' => '王小華',
                    'customer_company' => 'B 科技',
                    'customer_address' => '新北市板橋區',
                    'contact_name' => '李承辦',
                    'contact_title' => '資訊處／專案經理',
                    'contact_phone' => '02-8765-4321',
                    'contact_email' => 'lee@b-tech.com',
                    'keyman_name' => '陳總監',
                    'keyman_phone' => '02-8765-4000',
                    'keyman_email' => 'chen@b-tech.com',
                    'poc_date' => '2026-08-15',
                    'decision_date' => '2026-09-30',
                    'delivery_date' => '2026-10-31',
                    'complete_date' => '2026-11-30',
                ],
                'attachment' => [
                    'name' => '客戶需求規格書.pdf',
                    'size' => 245760,
                    'sizeLabel' => '240.0 KB',
                    'type' => 'application/pdf',
                    'url' => '#',
                ],
            ],
        ],
        'N260728001' => [
            'id' => 'N260728001',
            'status' => 'expiring',
            'statusLabel' => '即將到期',
            'title' => 'C 集團 | 跨國據點存取控管案',
            'dealerName' => '海外 Partner HK',
            'submittedAt' => '2026/05/02 11:15',
            'customer_company' => 'C 集團',
            'tax_id' => '87654321',
            'amount' => 'NT$ 1,200,000',
            'amountValue' => 1200000,
            'close_date' => '2026 / 08 / 30',
            'product_line' => 'ARPScanner、DHCPManager',
            'requirement' => '海外據點需統一 IP 管理政策，保護期即將到期。',
            'attachment' => ['name' => '專案簡報.pdf', 'url' => '#'],
            'booking_code' => 'N260728001',
            'dealer' => 'overseas',
            'protection' => '2026-07-15',
            'review' => [
                'result' => 'approved',
                'resultLabel' => '審核通過',
                'sales' => 'chen',
                'salesLabel' => '陳志明',
                'bookingCode' => 'N260728001',
                'note' => '',
                'reviewedAt' => '2026/05/03 09:30',
            ],
            'form' => [
                'source' => 'self',
                'oem_sales' => '陳志明',
                'customer_relation' => 'repeat',
                'competitors' => '海外據點同時評估其他 IP 管理方案',
                'products' => ['ARPScanner IP管理系統', 'DHCPManager DHCP管理系統'],
                'units' => ['2000-4999', '1000-1999'],
                'fields' => [
                    'oem_sales' => '陳志明',
                    'customer_company' => 'C 集團',
                    'customer_address' => '香港九龍觀塘區',
                    'contact_name' => '周經理',
                    'contact_title' => '資訊長室／專案經理',
                    'contact_phone' => '+852-2345-6789',
                    'contact_email' => 'chow@c-group.com',
                    'keyman_name' => '吳執行長',
                    'keyman_phone' => '+852-2345-6000',
                    'keyman_email' => 'wu@c-group.com',
                    'poc_date' => '2026-06-01',
                    'decision_date' => '2026-08-30',
                    'delivery_date' => '2026-09-30',
                    'complete_date' => '2026-10-31',
                ],
                'attachment' => [
                    'name' => '專案簡報.pdf',
                    'size' => 512000,
                    'sizeLabel' => '500.0 KB',
                    'type' => 'application/pdf',
                    'url' => '#',
                ],
            ],
        ],
        'N260728002' => [
            'id' => 'N260728002',
            'status' => 'rejected',
            'statusLabel' => '退回補件',
            'title' => 'D 數位 | 訪客管理評估案',
            'dealerName' => '台灣 XX 科技',
            'submittedAt' => '2026/07/10 16:05',
            'customer_company' => 'D 數位',
            'tax_id' => '55667788',
            'amount' => 'NT$ 350,000',
            'amountValue' => 350000,
            'close_date' => '2026 / 11 / 01',
            'product_line' => 'GAM 訪客管理',
            'requirement' => '客戶評估訪客管理方案，目前需求說明較簡略。',
            'attachment' => ['name' => '初步需求.docx', 'url' => '#'],
            'booking_code' => 'N260728002',
            'dealer' => 'tw',
            'protection' => '-',
            'review' => [
                'result' => 'insufficient',
                'resultLabel' => '資料不足，請補充',
                'sales' => 'lin',
                'salesLabel' => '林佳穎',
                'bookingCode' => 'N260728002',
                'note' => '請補充 Key Man 聯絡資訊與預計 POC 時程。',
                'reviewedAt' => '2026/07/11 09:20',
            ],
            'form' => [
                'source' => 'self',
                'oem_sales' => '林佳穎',
                'customer_relation' => 'first',
                'competitors' => '',
                'products' => ['MACManager MAC位址管理系統'],
                'units' => ['0-499'],
                'fields' => [
                    'oem_sales' => '林佳穎',
                    'customer_company' => 'D 數位',
                    'customer_address' => '台北市信義區',
                    'contact_name' => '張經理',
                    'contact_title' => '資訊部',
                    'contact_phone' => '02-2345-6789',
                    'contact_email' => 'contact@d-digital.com',
                    'keyman_name' => '',
                    'keyman_phone' => '',
                    'keyman_email' => '',
                    'poc_date' => '',
                    'decision_date' => '2026-11-01',
                    'delivery_date' => '2026-12-01',
                    'complete_date' => '2026-12-15',
                ],
            ],
        ],
        'N260728003' => [
            'id' => 'N260728003',
            'status' => 'expired',
            'statusLabel' => '已到期',
            'title' => 'E 集團 | 舊案保護期結束',
            'dealerName' => '原廠業務窗口',
            'submittedAt' => '2026/03/01 10:00',
            'customer_company' => 'E 集團',
            'tax_id' => '11223344',
            'amount' => 'NT$ 750,000',
            'amountValue' => 750000,
            'close_date' => '2026 / 06 / 30',
            'product_line' => 'IPLocator、ARPScanner',
            'requirement' => '保護期已結束，客戶暫無後續採購時程。',
            'attachment' => null,
            'booking_code' => 'N260728003',
            'dealer' => 'oem',
            'protection' => '2026-07-15',
            'review' => [
                'result' => 'approved',
                'resultLabel' => '審核通過',
                'sales' => 'huang',
                'salesLabel' => '黃建宏',
                'bookingCode' => 'N260728003',
                'note' => '',
                'reviewedAt' => '2026/03/02 14:00',
            ],
            'form' => [
                'source' => 'oem',
                'oem_sales' => '黃建宏',
                'customer_relation' => 'repeat',
                'competitors' => '',
                'products' => ['IPLocator IP位址解析模組', 'ARPScanner IP管理系統'],
                'units' => ['1000-1999', '500-999'],
                'fields' => [
                    'oem_sales' => '黃建宏',
                    'customer_company' => 'E 集團',
                    'customer_address' => '台中市西屯區',
                    'contact_name' => '許經理',
                    'contact_title' => '資訊部經理',
                    'contact_phone' => '04-2358-1234',
                    'contact_email' => 'hsu@e-group.com',
                    'keyman_name' => '鄭副總',
                    'keyman_phone' => '04-2358-1000',
                    'keyman_email' => 'cheng@e-group.com',
                    'poc_date' => '2026-04-01',
                    'decision_date' => '2026-06-30',
                    'delivery_date' => '2026-07-31',
                    'complete_date' => '2026-08-31',
                ],
            ],
        ],
        'N260728006' => [
            'id' => 'N260728006',
            'status' => 'cancelled',
            'statusLabel' => '已取消',
            'title' => 'F 製造 | 廠區網路盤點案',
            'dealerName' => '台灣 XX 科技',
            'submittedAt' => '2026/06/12 13:40',
            'customer_company' => 'F 製造',
            'tax_id' => '33445566',
            'amount' => 'NT$ 420,000',
            'amountValue' => 420000,
            'close_date' => '2026 / 09 / 01',
            'product_line' => 'ARPScanner、MACManager',
            'requirement' => '客戶內部組織調整，經銷商已取消此商機報備。',
            'attachment' => ['name' => '取消說明.pdf', 'url' => '#'],
            'booking_code' => 'N260728006',
            'dealer' => 'tw',
            'protection' => '-',
            'review' => [
                'result' => 'approved',
                'resultLabel' => '審核通過',
                'sales' => 'wu',
                'salesLabel' => '吳佩珊',
                'bookingCode' => 'N260728006',
                'note' => '原已核准；後由夥伴取消報備。',
                'reviewedAt' => '2026/06/13 09:10',
            ],
            'form' => [
                'source' => 'self',
                'oem_sales' => '吳佩珊',
                'customer_relation' => 'first',
                'competitors' => '',
                'products' => ['ARPScanner IP管理系統', 'MACManager MAC位址管理系統'],
                'units' => ['500-999', '0-499'],
                'fields' => [
                    'oem_sales' => '吳佩珊',
                    'customer_company' => 'F 製造',
                    'customer_address' => '桃園市龜山區',
                    'contact_name' => '蔡課長',
                    'contact_title' => '廠務／資訊課',
                    'contact_phone' => '03-327-8899',
                    'contact_email' => 'tsai@f-mfg.com',
                    'keyman_name' => '葉廠長',
                    'keyman_phone' => '03-327-8800',
                    'keyman_email' => 'yeh@f-mfg.com',
                    'poc_date' => '2026-07-01',
                    'decision_date' => '2026-09-01',
                    'delivery_date' => '2026-10-01',
                    'complete_date' => '2026-10-31',
                ],
                'attachment' => [
                    'name' => '取消說明.pdf',
                    'size' => 81920,
                    'sizeLabel' => '80.0 KB',
                    'type' => 'application/pdf',
                    'url' => '#',
                ],
            ],
        ],
        'N260728007' => [
            'id' => 'N260728007',
            'status' => 'completed',
            'statusLabel' => '已結案',
            'title' => 'G 醫院 | 醫療網段 IP 管理導入案',
            'dealerName' => '原廠業務窗口',
            'submittedAt' => '2025/11/08 10:25',
            'customer_company' => 'G 醫院',
            'tax_id' => '99887766',
            'amount' => 'NT$ 980,000',
            'amountValue' => 980000,
            'close_date' => '2026 / 02 / 28',
            'product_line' => 'IPLocator、DHCPManager',
            'requirement' => '保護期已到期，無需再延長保護，本案結案。',
            'attachment' => ['name' => '驗收報告.pdf', 'url' => '#'],
            'booking_code' => 'N260728007',
            'dealer' => 'oem',
            'protection' => '-',
            'review' => [
                'result' => 'approved',
                'resultLabel' => '審核通過',
                'sales' => 'lin',
                'salesLabel' => '林佳穎',
                'bookingCode' => 'N260728007',
                'note' => '保護期已結束，無需再保護，已結案。',
                'reviewedAt' => '2025/11/09 11:00',
            ],
            'form' => [
                'source' => 'oem',
                'oem_sales' => '林佳穎',
                'customer_relation' => 'repeat',
                'competitors' => '',
                'products' => ['IPLocator IP位址解析模組', 'DHCPManager DHCP管理系統'],
                'units' => ['2000-4999', '1000-1999'],
                'fields' => [
                    'oem_sales' => '林佳穎',
                    'customer_company' => 'G 醫院',
                    'customer_address' => '高雄市苓雅區',
                    'contact_name' => '方主任',
                    'contact_title' => '資訊室主任',
                    'contact_phone' => '07-312-3456',
                    'contact_email' => 'fang@g-hospital.org',
                    'keyman_name' => '沈副院長',
                    'keyman_phone' => '07-312-3000',
                    'keyman_email' => 'shen@g-hospital.org',
                    'poc_date' => '2025-12-01',
                    'decision_date' => '2026-02-28',
                    'delivery_date' => '2026-03-15',
                    'complete_date' => '2026-03-31',
                ],
                'attachment' => [
                    'name' => '驗收報告.pdf',
                    'size' => 307200,
                    'sizeLabel' => '300.0 KB',
                    'type' => 'application/pdf',
                    'url' => '#',
                ],
            ],
        ],
        'N260728008' => [
            'id' => 'N260728008',
            'status' => 'invalid',
            'statusLabel' => '已失效',
            'title' => 'H 零售 | 門市訪客管理評估案',
            'dealerName' => '海外 Partner SG',
            'submittedAt' => '2026/07/05 15:10',
            'customer_company' => 'H 零售',
            'tax_id' => '66778899',
            'amount' => 'NT$ 260,000',
            'amountValue' => 260000,
            'close_date' => '2026 / 10 / 01',
            'product_line' => 'MACManager',
            'requirement' => '審核判定已有相同／重複商機，本案失效。',
            'attachment' => ['name' => '報備資料.pdf', 'url' => '#'],
            'booking_code' => 'N260728008',
            'dealer' => 'overseas',
            'protection' => '-',
            'review' => [
                'result' => 'duplicate',
                'resultLabel' => '已有相同／重複商機',
                'sales' => 'wang',
                'salesLabel' => '王小華',
                'bookingCode' => 'N260728008',
                'note' => '與既有報備案件重複，本案改為已失效。',
                'reviewedAt' => '2026/07/06 09:45',
            ],
            'form' => [
                'source' => 'self',
                'oem_sales' => '王小華',
                'customer_relation' => 'first',
                'competitors' => '',
                'products' => ['MACManager MAC位址管理系統'],
                'units' => ['0-499'],
                'fields' => [
                    'oem_sales' => '王小華',
                    'customer_company' => 'H 零售',
                    'customer_address' => '新加坡市中心',
                    'contact_name' => 'Tan 經理',
                    'contact_title' => 'IT Manager',
                    'contact_phone' => '+65-6123-4567',
                    'contact_email' => 'tan@h-retail.sg',
                    'keyman_name' => 'Lim 總監',
                    'keyman_phone' => '+65-6123-4000',
                    'keyman_email' => 'lim@h-retail.sg',
                    'poc_date' => '2026-08-01',
                    'decision_date' => '2026-10-01',
                    'delivery_date' => '2026-11-01',
                    'complete_date' => '2026-11-30',
                ],
                'attachment' => [
                    'name' => '報備資料.pdf',
                    'size' => 163840,
                    'sizeLabel' => '160.0 KB',
                    'type' => 'application/pdf',
                    'url' => '#',
                ],
            ],
        ],
    ],
    'isActive' => function ($page, $path) {
        $current = trim($page->getPath(), '/');
        $target = trim($path, '/');

        if ($target === '') {
            return $current === '' ? 'active' : '';
        }

        return ($current === $target || str_starts_with($current . '/', $target . '/'))
            ? 'active'
            : '';
    },
];
